# Generated by Django 3.0.4 on 2020-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200318_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='user',
            name='recents',
            field=models.CharField(default='', max_length=800),
        ),
    ]
